<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\User;
use App\Models\Category;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get vendors and categories
        $vendors = User::where('user_type', 'vendor')->get();
        $categories = Category::all();
        
        $products = [
            [
                'title_ar' => 'آيفون 15 برو ماكس 256 جيجا',
                'title_en' => 'iPhone 15 Pro Max 256GB',
                'description_ar' => 'آيفون 15 برو ماكس بذاكرة 256 جيجابايت، حالة ممتازة، مع الشاحن والسماعات الأصلية، ضمان سنة كاملة.',
                'description_en' => 'iPhone 15 Pro Max 256GB, excellent condition, with original charger and headphones, one year warranty.',
                'price' => 45000,
                'original_price' => 48000,
                'currency' => 'EGP',
                'condition' => 'new',
                'status' => 'active',
                'location_governorate' => 'القاهرة',
                'location_city' => 'مدينة نصر',
                'contact_phone' => '01012345679',
                'contact_whatsapp' => '01012345679',
                'is_negotiable' => true,
                'is_featured' => true,
                'views_count' => 245,
                'category_name' => 'الإلكترونيات',
            ],
            [
                'title_ar' => 'لابتوب ديل انسبايرون 15 كور i7',
                'title_en' => 'Dell Inspiron 15 Core i7 Laptop',
                'description_ar' => 'لابتوب ديل انسبايرون 15 بمعالج كور i7 الجيل العاشر، رام 16 جيجا، هارد SSD 512 جيجا، كارت شاشة منفصل.',
                'description_en' => 'Dell Inspiron 15 with 10th Gen Core i7, 16GB RAM, 512GB SSD, dedicated graphics card.',
                'price' => 28000,
                'original_price' => 32000,
                'currency' => 'EGP',
                'condition' => 'used',
                'status' => 'active',
                'location_governorate' => 'الجيزة',
                'location_city' => 'المهندسين',
                'contact_phone' => '01123456780',
                'is_negotiable' => true,
                'is_featured' => false,
                'views_count' => 156,
                'category_name' => 'الإلكترونيات',
            ],
            [
                'title_ar' => 'فستان سهرة أنيق باللون الأزرق',
                'title_en' => 'Elegant Blue Evening Dress',
                'description_ar' => 'فستان سهرة راقي باللون الأزرق الملكي، مقاس M، قماش شيفون عالي الجودة، مناسب للمناسبات الخاصة.',
                'description_en' => 'Elegant royal blue evening dress, size M, high quality chiffon fabric, perfect for special occasions.',
                'price' => 850,
                'currency' => 'EGP',
                'condition' => 'new',
                'status' => 'active',
                'location_governorate' => 'الجيزة',
                'location_city' => 'المهندسين',
                'contact_phone' => '01123456780',
                'is_negotiable' => false,
                'is_featured' => true,
                'views_count' => 89,
                'category_name' => 'الخدمات',
            ],
            [
                'title_ar' => 'كتاب البرمجة بلغة Python للمبتدئين',
                'title_en' => 'Python Programming for Beginners Book',
                'description_ar' => 'كتاب شامل لتعلم البرمجة بلغة Python من الصفر، يحتوي على أمثلة عملية ومشاريع تطبيقية، حالة ممتازة.',
                'description_en' => 'Comprehensive book for learning Python programming from scratch, contains practical examples and projects.',
                'price' => 120,
                'currency' => 'EGP',
                'condition' => 'used',
                'status' => 'active',
                'location_governorate' => 'الإسكندرية',
                'location_city' => 'الأزاريطة',
                'contact_phone' => '01234567891',
                'is_negotiable' => true,
                'is_featured' => false,
                'views_count' => 67,
                'category_name' => 'تدريس وتدريب',
            ],
            [
                'title_ar' => 'طقم أريكة مودرن 3+2+1',
                'title_en' => 'Modern Sofa Set 3+2+1',
                'description_ar' => 'طقم أريكة مودرن مكون من 3 مقاعد + 2 مقعد + مقعد واحد، قماش مخمل فاخر، لون بيج، حالة ممتازة.',
                'description_en' => 'Modern sofa set consisting of 3+2+1 seats, luxury velvet fabric, beige color, excellent condition.',
                'price' => 12500,
                'original_price' => 15000,
                'currency' => 'EGP',
                'condition' => 'used',
                'status' => 'active',
                'location_governorate' => 'الشرقية',
                'location_city' => 'الزقازيق',
                'contact_phone' => '01345678902',
                'is_negotiable' => true,
                'is_featured' => false,
                'views_count' => 134,
                'category_name' => 'الخدمات',
            ],
            [
                'title_ar' => 'دراجة هوائية جبلية احترافية',
                'title_en' => 'Professional Mountain Bike',
                'description_ar' => 'دراجة هوائية جبلية احترافية، 21 سرعة، إطار ألومنيوم خفيف، مكابح قرصية، حالة ممتازة، مستعملة قليلاً.',
                'description_en' => 'Professional mountain bike, 21 speeds, lightweight aluminum frame, disc brakes, excellent condition.',
                'price' => 3200,
                'currency' => 'EGP',
                'condition' => 'used',
                'status' => 'active',
                'location_governorate' => 'المنوفية',
                'location_city' => 'شبين الكوم',
                'contact_phone' => '01456789013',
                'is_negotiable' => true,
                'is_featured' => true,
                'views_count' => 98,
                'category_name' => 'دراجات نارية',
            ],
            [
                'title_ar' => 'جلسة عناية كاملة للوجه والبشرة',
                'title_en' => 'Complete Facial and Skin Care Session',
                'description_ar' => 'جلسة عناية كاملة للوجه تشمل تنظيف عميق، تقشير، ماسك مغذي، وترطيب، باستخدام منتجات طبيعية عالية الجودة.',
                'description_en' => 'Complete facial care session including deep cleansing, exfoliation, nourishing mask, and moisturizing.',
                'price' => 250,
                'currency' => 'EGP',
                'condition' => 'new',
                'status' => 'active',
                'location_governorate' => 'القليوبية',
                'location_city' => 'بنها',
                'contact_phone' => '01567890124',
                'is_negotiable' => false,
                'is_featured' => true,
                'views_count' => 187,
                'category_name' => 'الخدمات',
            ],
            [
                'title_ar' => 'قطع غيار تويوتا كامري موديل 2018',
                'title_en' => 'Toyota Camry 2018 Spare Parts',
                'description_ar' => 'قطع غيار أصلية لسيارة تويوتا كامري موديل 2018، متوفر جميع القطع، أسعار منافسة، ضمان 6 شهور.',
                'description_en' => 'Original spare parts for Toyota Camry 2018, all parts available, competitive prices, 6 months warranty.',
                'price' => 1500,
                'currency' => 'EGP',
                'condition' => 'new',
                'status' => 'active',
                'location_governorate' => 'البحيرة',
                'location_city' => 'دمنهور',
                'contact_phone' => '01678901235',
                'is_negotiable' => true,
                'is_featured' => false,
                'views_count' => 76,
                'category_name' => 'مركبات',
            ],
            [
                'title_ar' => 'كيك عيد ميلاد بالشوكولاتة',
                'title_en' => 'Chocolate Birthday Cake',
                'description_ar' => 'كيك عيد ميلاد فاخر بالشوكولاتة البلجيكية، يمكن تخصيص التصميم والكتابة، طازج يومياً، متوفر بأحجام مختلفة.',
                'description_en' => 'Luxury chocolate birthday cake with Belgian chocolate, customizable design and writing, fresh daily.',
                'price' => 180,
                'currency' => 'EGP',
                'condition' => 'new',
                'status' => 'active',
                'location_governorate' => 'الغربية',
                'location_city' => 'طنطا',
                'contact_phone' => '01789012346',
                'is_negotiable' => false,
                'is_featured' => false,
                'views_count' => 145,
                'category_name' => 'طعام وفواكه',
            ],
            [
                'title_ar' => 'جهاز كمبيوتر مكتبي للألعاب',
                'title_en' => 'Gaming Desktop Computer',
                'description_ar' => 'جهاز كمبيوتر مكتبي مخصص للألعاب، معالج AMD Ryzen 7، كارت شاشة RTX 3060، رام 32 جيجا، هارد SSD 1 تيرا.',
                'description_en' => 'Gaming desktop computer with AMD Ryzen 7, RTX 3060 graphics card, 32GB RAM, 1TB SSD.',
                'price' => 35000,
                'currency' => 'EGP',
                'condition' => 'new',
                'status' => 'active',
                'location_governorate' => 'كفر الشيخ',
                'location_city' => 'كفر الشيخ',
                'contact_phone' => '01890123457',
                'is_negotiable' => true,
                'is_featured' => true,
                'views_count' => 203,
                'category_name' => 'الإلكترونيات',
            ],
            [
                'title_ar' => 'ملابس أطفال صيفية مقاس 2-4 سنوات',
                'title_en' => 'Summer Kids Clothes Size 2-4 Years',
                'description_ar' => 'مجموعة ملابس أطفال صيفية عالية الجودة، قطن 100%، ألوان زاهية، مقاسات من 2 إلى 4 سنوات، آمنة ومريحة.',
                'description_en' => 'High quality summer kids clothes collection, 100% cotton, bright colors, sizes 2-4 years.',
                'price' => 320,
                'currency' => 'EGP',
                'condition' => 'new',
                'status' => 'active',
                'location_governorate' => 'الدقهلية',
                'location_city' => 'المنصورة',
                'contact_phone' => '01901234568',
                'is_negotiable' => false,
                'is_featured' => false,
                'views_count' => 89,
                'category_name' => 'حيوانات',
            ],
            [
                'title_ar' => 'سامسونج جالاكسي S23 الترا',
                'title_en' => 'Samsung Galaxy S23 Ultra',
                'description_ar' => 'سامسونج جالاكسي S23 الترا، ذاكرة 512 جيجا، رام 12 جيجا، كاميرا 200 ميجابكسل، حالة ممتازة مع العلبة الأصلية.',
                'description_en' => 'Samsung Galaxy S23 Ultra, 512GB storage, 12GB RAM, 200MP camera, excellent condition with original box.',
                'price' => 42000,
                'original_price' => 45000,
                'currency' => 'EGP',
                'condition' => 'used',
                'status' => 'active',
                'location_governorate' => 'القاهرة',
                'location_city' => 'وسط البلد',
                'contact_phone' => '01012345679',
                'is_negotiable' => true,
                'is_featured' => true,
                'views_count' => 312,
                'category_name' => 'الإلكترونيات',
            ],
            [
                'title_ar' => 'بدلة رجالي كلاسيكية رمادية',
                'title_en' => 'Classic Gray Men Suit',
                'description_ar' => 'بدلة رجالي كلاسيكية باللون الرمادي، قماش صوف إيطالي، مقاس 50، مناسبة للمناسبات الرسمية والأعراس.',
                'description_en' => 'Classic gray men suit, Italian wool fabric, size 50, perfect for formal occasions and weddings.',
                'price' => 1200,
                'currency' => 'EGP',
                'condition' => 'new',
                'status' => 'active',
                'location_governorate' => 'الجيزة',
                'location_city' => 'المهندسين',
                'contact_phone' => '01123456780',
                'is_negotiable' => false,
                'is_featured' => false,
                'views_count' => 67,
                'category_name' => 'الخدمات',
            ],
            [
                'title_ar' => 'دورة تعليم اللغة الإنجليزية أونلاين',
                'title_en' => 'Online English Learning Course',
                'description_ar' => 'دورة شاملة لتعليم اللغة الإنجليزية أونلاين، 3 مستويات، شهادة معتمدة، مدرس خبرة 10 سنوات، جلسات تفاعلية.',
                'description_en' => 'Comprehensive online English learning course, 3 levels, certified certificate, 10 years experienced teacher.',
                'price' => 800,
                'currency' => 'EGP',
                'condition' => 'new',
                'status' => 'active',
                'location_governorate' => 'الإسكندرية',
                'location_city' => 'الأزاريطة',
                'contact_phone' => '01234567891',
                'is_negotiable' => true,
                'is_featured' => true,
                'views_count' => 234,
                'category_name' => 'تدريس وتدريب',
            ],
            [
                'title_ar' => 'طاولة طعام خشبية 6 كراسي',
                'title_en' => 'Wooden Dining Table with 6 Chairs',
                'description_ar' => 'طاولة طعام من الخشب الطبيعي مع 6 كراسي مبطنة، تصميم كلاسيكي أنيق، حالة ممتازة، مناسبة للعائلات الكبيرة.',
                'description_en' => 'Natural wood dining table with 6 upholstered chairs, elegant classic design, excellent condition.',
                'price' => 8500,
                'original_price' => 10000,
                'currency' => 'EGP',
                'condition' => 'used',
                'status' => 'active',
                'location_governorate' => 'الشرقية',
                'location_city' => 'الزقازيق',
                'contact_phone' => '01345678902',
                'is_negotiable' => true,
                'is_featured' => false,
                'views_count' => 156,
                'category_name' => 'الخدمات',
            ],
            [
                'title_ar' => 'حذاء رياضي نايكي اير ماكس',
                'title_en' => 'Nike Air Max Sports Shoes',
                'description_ar' => 'حذاء رياضي نايكي اير ماكس أصلي، مقاس 42، لون أسود وأبيض، مريح جداً للجري والرياضة، حالة ممتازة.',
                'description_en' => 'Original Nike Air Max sports shoes, size 42, black and white color, very comfortable for running.',
                'price' => 1800,
                'currency' => 'EGP',
                'condition' => 'used',
                'status' => 'active',
                'location_governorate' => 'المنوفية',
                'location_city' => 'شبين الكوم',
                'contact_phone' => '01456789013',
                'is_negotiable' => true,
                'is_featured' => false,
                'views_count' => 123,
                'category_name' => 'الخدمات',
            ],
            [
                'title_ar' => 'جلسة مساج استرخائي كاملة',
                'title_en' => 'Complete Relaxation Massage Session',
                'description_ar' => 'جلسة مساج استرخائي كاملة للجسم، 60 دقيقة، باستخدام زيوت طبيعية عطرية، في بيئة هادئة ومريحة.',
                'description_en' => 'Complete body relaxation massage session, 60 minutes, using natural aromatic oils in a calm environment.',
                'price' => 300,
                'currency' => 'EGP',
                'condition' => 'new',
                'status' => 'active',
                'location_governorate' => 'القليوبية',
                'location_city' => 'بنها',
                'contact_phone' => '01567890124',
                'is_negotiable' => false,
                'is_featured' => true,
                'views_count' => 198,
                'category_name' => 'الخدمات',
            ],
            [
                'title_ar' => 'إطارات سيارة ميشلان جديدة',
                'title_en' => 'New Michelin Car Tires',
                'description_ar' => 'إطارات سيارة ميشلان جديدة، مقاس 205/55 R16، مناسبة لمعظم السيارات، جودة عالية، ضمان سنتين.',
                'description_en' => 'New Michelin car tires, size 205/55 R16, suitable for most cars, high quality, 2 years warranty.',
                'price' => 2400,
                'currency' => 'EGP',
                'condition' => 'new',
                'status' => 'active',
                'location_governorate' => 'البحيرة',
                'location_city' => 'دمنهور',
                'contact_phone' => '01678901235',
                'is_negotiable' => true,
                'is_featured' => false,
                'views_count' => 87,
                'category_name' => 'مركبات',
            ],
            [
                'title_ar' => 'تورتة زفاف بالفانيليا والفراولة',
                'title_en' => 'Vanilla Strawberry Wedding Cake',
                'description_ar' => 'تورتة زفاف فاخرة بطعم الفانيليا والفراولة، 3 طوابق، تصميم رومانسي أنيق، تكفي 50 شخص، طازجة يومياً.',
                'description_en' => 'Luxury vanilla strawberry wedding cake, 3 tiers, elegant romantic design, serves 50 people, fresh daily.',
                'price' => 1500,
                'currency' => 'EGP',
                'condition' => 'new',
                'status' => 'active',
                'location_governorate' => 'الغربية',
                'location_city' => 'طنطا',
                'contact_phone' => '01789012346',
                'is_negotiable' => false,
                'is_featured' => true,
                'views_count' => 267,
                'category_name' => 'طعام وفواكه',
            ],
            [
                'title_ar' => 'شاشة كمبيوتر منحنية 27 بوصة',
                'title_en' => '27 Inch Curved Computer Monitor',
                'description_ar' => 'شاشة كمبيوتر منحنية 27 بوصة، دقة 4K، معدل تحديث 144Hz، مناسبة للألعاب والتصميم، حالة ممتازة.',
                'description_en' => '27 inch curved computer monitor, 4K resolution, 144Hz refresh rate, perfect for gaming and design.',
                'price' => 6500,
                'currency' => 'EGP',
                'condition' => 'used',
                'status' => 'active',
                'location_governorate' => 'كفر الشيخ',
                'location_city' => 'كفر الشيخ',
                'contact_phone' => '01890123457',
                'is_negotiable' => true,
                'is_featured' => false,
                'views_count' => 134,
                'category_name' => 'الإلكترونيات',
            ],
        ];

        foreach ($products as $index => $productData) {
            // Get random vendor and category
            $vendor = $vendors->random();
            $category = $categories->where('name', $productData['category_name'])->first() 
                       ?? $categories->first();
            
            // Remove category_name from product data
            unset($productData['category_name']);
            
            // Get first vendor from existing vendors table
            $vendorFromVendorsTable = \App\Models\Vendor::first();
            if (!$vendorFromVendorsTable) {
                // Create a simple vendor if none exists
                $vendorFromVendorsTable = \App\Models\Vendor::create([
                    'store_name' => 'متجر تجريبي',
                    'store_name_ar' => 'متجر تجريبي',
                    'email' => 'vendor@example.com',
                    'phone' => '01000000000',
                    'city' => 'القاهرة',
                    'is_active' => true,
                    'is_verified' => true,
                ]);
            }
            
            Product::create([
                'vendor_id' => $vendorFromVendorsTable->id,
                'category_id' => $category->id,
                'name' => $productData['title_en'] ?? $productData['title_ar'],
                'name_ar' => $productData['title_ar'],
                'description' => $productData['description_en'] ?? $productData['description_ar'],
                'description_ar' => $productData['description_ar'],
                'sku' => 'SKU-' . strtoupper(Str::random(8)),
                'price' => $productData['price'],
                'sale_price' => $productData['original_price'] ?? null,
                'slug' => Str::slug($productData['title_ar']) . '-' . Str::random(6),
                'is_active' => $productData['status'] === 'active',
                'is_featured' => $productData['is_featured'] ?? false,
            ]);
        }
    }
}
