<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\User;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Create 10 customers
        $customers = [
            [
                'name' => 'أحمد محمد علي',
                'email' => 'ahmed@example.com',
                'phone' => '01012345678',
                'governorate' => 'القاهرة',
                'city' => 'مدينة نصر',
                'user_type' => 'customer',
                'registration_completed' => true,
            ],
            [
                'name' => 'فاطمة حسن محمود',
                'email' => 'fatma@example.com',
                'phone' => '01123456789',
                'governorate' => 'الجيزة',
                'city' => 'الدقي',
                'user_type' => 'customer',
                'registration_completed' => true,
            ],
            [
                'name' => 'محمد أحمد السيد',
                'email' => 'mohamed@example.com',
                'phone' => '01234567890',
                'governorate' => 'الإسكندرية',
                'city' => 'سموحة',
                'user_type' => 'customer',
                'registration_completed' => true,
            ],
            [
                'name' => 'نور الدين عبدالله',
                'email' => 'nour@example.com',
                'phone' => '01345678901',
                'governorate' => 'الشرقية',
                'city' => 'الزقازيق',
                'user_type' => 'customer',
                'registration_completed' => true,
            ],
            [
                'name' => 'مريم عبدالرحمن',
                'email' => 'mariam@example.com',
                'phone' => '01456789012',
                'governorate' => 'المنوفية',
                'city' => 'شبين الكوم',
                'user_type' => 'customer',
                'registration_completed' => true,
            ],
            [
                'name' => 'عبدالرحمن صلاح',
                'email' => 'abdelrahman@example.com',
                'phone' => '01567890123',
                'governorate' => 'القليوبية',
                'city' => 'بنها',
                'user_type' => 'customer',
                'registration_completed' => true,
            ],
            [
                'name' => 'هدى إبراهيم',
                'email' => 'hoda@example.com',
                'phone' => '01678901234',
                'governorate' => 'البحيرة',
                'city' => 'دمنهور',
                'user_type' => 'customer',
                'registration_completed' => true,
            ],
            [
                'name' => 'يوسف محمد',
                'email' => 'youssef@example.com',
                'phone' => '01789012345',
                'governorate' => 'الغربية',
                'city' => 'طنطا',
                'user_type' => 'customer',
                'registration_completed' => true,
            ],
            [
                'name' => 'سارة أحمد',
                'email' => 'sara@example.com',
                'phone' => '01890123456',
                'governorate' => 'كفر الشيخ',
                'city' => 'كفر الشيخ',
                'user_type' => 'customer',
                'registration_completed' => true,
            ],
            [
                'name' => 'عمر عبدالله',
                'email' => 'omar@example.com',
                'phone' => '01901234567',
                'governorate' => 'الدقهلية',
                'city' => 'المنصورة',
                'user_type' => 'customer',
                'registration_completed' => true,
            ],
        ];

        foreach ($customers as $customer) {
            User::create(array_merge($customer, [
                'password' => Hash::make('password123'),
                'email_verified_at' => now(),
            ]));
        }

        // Create 10 vendors (stores)
        $vendors = [
            [
                'name' => 'خالد محمد التاجر',
                'email' => 'khaled.store@example.com',
                'phone' => '01012345679',
                'governorate' => 'القاهرة',
                'city' => 'وسط البلد',
                'user_type' => 'vendor',
                'registration_completed' => true,
                'store_name' => 'متجر الإلكترونيات الحديثة',
                'store_phone' => '0227654321',
                'store_description' => 'متجر متخصص في بيع أحدث الأجهزة الإلكترونية والهواتف الذكية بأفضل الأسعار وأعلى جودة في السوق المصري.',
                'store_address' => 'شارع طلعت حرب، وسط البلد، القاهرة',
                'store_latitude' => 30.0444,
                'store_longitude' => 31.2357,
                'store_verified' => true,
                'store_rating' => 4.5,
                'store_reviews_count' => 127,
                'store_created_at' => now()->subMonths(8),
            ],
            [
                'name' => 'أمينة حسن',
                'email' => 'amina.fashion@example.com',
                'phone' => '01123456780',
                'governorate' => 'الجيزة',
                'city' => 'المهندسين',
                'user_type' => 'vendor',
                'registration_completed' => true,
                'store_name' => 'بوتيك أمينة للأزياء',
                'store_phone' => '0233456789',
                'store_description' => 'بوتيك متخصص في الأزياء النسائية العصرية والكلاسيكية، نقدم أجمل التصاميم العالمية والمحلية بجودة عالية.',
                'store_address' => 'شارع جامعة الدول العربية، المهندسين، الجيزة',
                'store_latitude' => 30.0626,
                'store_longitude' => 31.2497,
                'store_verified' => true,
                'store_rating' => 4.8,
                'store_reviews_count' => 89,
                'store_created_at' => now()->subMonths(6),
            ],
            [
                'name' => 'محمود عبدالفتاح',
                'email' => 'mahmoud.books@example.com',
                'phone' => '01234567891',
                'governorate' => 'الإسكندرية',
                'city' => 'الأزاريطة',
                'user_type' => 'vendor',
                'registration_completed' => true,
                'store_name' => 'مكتبة النور للكتب',
                'store_phone' => '034567890',
                'store_description' => 'مكتبة شاملة تضم أكبر مجموعة من الكتب العربية والأجنبية في مختلف المجالات العلمية والأدبية والثقافية.',
                'store_address' => 'شارع فؤاد، الأزاريطة، الإسكندرية',
                'store_latitude' => 31.2001,
                'store_longitude' => 29.9187,
                'store_verified' => true,
                'store_rating' => 4.3,
                'store_reviews_count' => 156,
                'store_created_at' => now()->subMonths(12),
            ],
            [
                'name' => 'رانيا أحمد',
                'email' => 'rania.home@example.com',
                'phone' => '01345678902',
                'governorate' => 'الشرقية',
                'city' => 'الزقازيق',
                'user_type' => 'vendor',
                'registration_completed' => true,
                'store_name' => 'متجر المنزل العصري',
                'store_phone' => '0552345678',
                'store_description' => 'متجر متخصص في الأثاث المنزلي والديكورات العصرية، نوفر كل ما تحتاجه لجعل منزلك أكثر جمالاً وراحة.',
                'store_address' => 'شارع الجمهورية، الزقازيق، الشرقية',
                'store_latitude' => 30.5877,
                'store_longitude' => 31.5022,
                'store_verified' => false,
                'store_rating' => 4.1,
                'store_reviews_count' => 43,
                'store_created_at' => now()->subMonths(4),
            ],
            [
                'name' => 'طارق السيد',
                'email' => 'tarek.sports@example.com',
                'phone' => '01456789013',
                'governorate' => 'المنوفية',
                'city' => 'شبين الكوم',
                'user_type' => 'vendor',
                'registration_completed' => true,
                'store_name' => 'متجر البطل الرياضي',
                'store_phone' => '0482345678',
                'store_description' => 'متجر رياضي شامل يوفر جميع المعدات والملابس الرياضية للرجال والنساء والأطفال من أفضل الماركات العالمية.',
                'store_address' => 'شارع الجلاء، شبين الكوم، المنوفية',
                'store_latitude' => 30.5594,
                'store_longitude' => 31.0118,
                'store_verified' => true,
                'store_rating' => 4.6,
                'store_reviews_count' => 78,
                'store_created_at' => now()->subMonths(7),
            ],
            [
                'name' => 'نادية محمد',
                'email' => 'nadia.beauty@example.com',
                'phone' => '01567890124',
                'governorate' => 'القليوبية',
                'city' => 'بنها',
                'user_type' => 'vendor',
                'registration_completed' => true,
                'store_name' => 'صالون نادية للجمال',
                'store_phone' => '0132345678',
                'store_description' => 'صالون تجميل متكامل يقدم جميع خدمات العناية بالشعر والبشرة والأظافر باستخدام أحدث التقنيات والمنتجات.',
                'store_address' => 'شارع الثورة، بنها، القليوبية',
                'store_latitude' => 30.4643,
                'store_longitude' => 31.1839,
                'store_verified' => true,
                'store_rating' => 4.9,
                'store_reviews_count' => 234,
                'store_created_at' => now()->subMonths(15),
            ],
            [
                'name' => 'حسام الدين علي',
                'email' => 'hossam.auto@example.com',
                'phone' => '01678901235',
                'governorate' => 'البحيرة',
                'city' => 'دمنهور',
                'user_type' => 'vendor',
                'registration_completed' => true,
                'store_name' => 'ورشة حسام لقطع غيار السيارات',
                'store_phone' => '0453456789',
                'store_description' => 'ورشة متخصصة في قطع غيار السيارات الأصلية والبديلة، نوفر جميع قطع الغيار للسيارات المختلفة بأسعار منافسة.',
                'store_address' => 'طريق الإسكندرية، دمنهور، البحيرة',
                'store_latitude' => 31.0364,
                'store_longitude' => 30.4707,
                'store_verified' => false,
                'store_rating' => 4.2,
                'store_reviews_count' => 67,
                'store_created_at' => now()->subMonths(5),
            ],
            [
                'name' => 'سمية إبراهيم',
                'email' => 'somaya.food@example.com',
                'phone' => '01789012346',
                'governorate' => 'الغربية',
                'city' => 'طنطا',
                'user_type' => 'vendor',
                'registration_completed' => true,
                'store_name' => 'مطبخ سمية للحلويات',
                'store_phone' => '0403456789',
                'store_description' => 'مطبخ متخصص في صنع الحلويات الشرقية والغربية الطازجة، نقدم أشهى الحلويات للمناسبات والأعياد.',
                'store_address' => 'شارع الجيش، طنطا، الغربية',
                'store_latitude' => 30.7865,
                'store_longitude' => 31.0004,
                'store_verified' => true,
                'store_rating' => 4.7,
                'store_reviews_count' => 145,
                'store_created_at' => now()->subMonths(9),
            ],
            [
                'name' => 'وليد محمود',
                'email' => 'walid.tech@example.com',
                'phone' => '01890123457',
                'governorate' => 'كفر الشيخ',
                'city' => 'كفر الشيخ',
                'user_type' => 'vendor',
                'registration_completed' => true,
                'store_name' => 'مركز وليد للكمبيوتر',
                'store_phone' => '0473456789',
                'store_description' => 'مركز متخصص في بيع وصيانة أجهزة الكمبيوتر واللابتوب، نوفر أحدث الأجهزة وقطع الغيار بضمان شامل.',
                'store_address' => 'شارع الجمهورية، كفر الشيخ',
                'store_latitude' => 31.1107,
                'store_longitude' => 30.9388,
                'store_verified' => true,
                'store_rating' => 4.4,
                'store_reviews_count' => 92,
                'store_created_at' => now()->subMonths(10),
            ],
            [
                'name' => 'منى عبدالعزيز',
                'email' => 'mona.kids@example.com',
                'phone' => '01901234568',
                'governorate' => 'الدقهلية',
                'city' => 'المنصورة',
                'user_type' => 'vendor',
                'registration_completed' => true,
                'store_name' => 'عالم الأطفال السعيد',
                'store_phone' => '0503456789',
                'store_description' => 'متجر متخصص في ملابس وألعاب الأطفال من جميع الأعمار، نوفر أجمل وأحدث التصاميم الآمنة والمريحة للأطفال.',
                'store_address' => 'شارع الجمهورية، المنصورة، الدقهلية',
                'store_latitude' => 31.0364,
                'store_longitude' => 31.3807,
                'store_verified' => false,
                'store_rating' => 4.0,
                'store_reviews_count' => 56,
                'store_created_at' => now()->subMonths(3),
            ],
        ];

        foreach ($vendors as $vendor) {
            User::create(array_merge($vendor, [
                'password' => Hash::make('password123'),
                'email_verified_at' => now(),
            ]));
        }
    }
}
